language: ruby
env:
  - DOMAIN=.example.com APP_MAILER_FROM=me@example.com BASE_URL=localhost.local APP_MAILER_FROM=john@example.com APP_MAILER_RETURN_PATH=john@example.comCOVERALLS_REPO_TOKEN=CV3tGg1C0E7otBaxvTY3gQ7i10cFAo9f7
gemfile:
  - gemfiles/Gemfile.rails-head
matrix:
  allow_failures:
    - gemfile: gemfiles/Gemfile.rails-head
  include:
    - gemfile: Gemfile
      rvm: 2.1.2
services:
  - mongodb
rvm:
  - 1.9.3
  - 2.0.0
  - 2.1.2
  - ruby-head
script: bundle exec rspec
